url: "https://gonzalezmendez.github.io"
baseurl: ""


<!DOCTYPE html>
<html>
<head>
    <title>Alfredo Gonz√°lez | Portafolio</title>
</head>
<body>
    <h1>Bienvenido a mi sitio</h1>
</body>
</html>
