remote_theme: pages-themes/modernist@v0.2.0
title: Alfredo GonzÃ¡lez MÃ©ndez
description: ğŸ—ï¸ Data Scientist (+8y) | ğŸ“Š BI & Data Architecture Specialist | ğŸ§  ML & Predictive Analytics | ğŸ¨ Data Storytelling | Transformando datos en estrategia.
show_downloads: false

github_username: gonzalezmendez
