remote_theme: pages-themes/modernist@v0.2.0
title: Alfredo González Méndez
description: Mi portafolio personal
show_downloads: false

logo: https://avatars.githubusercontent.com/u/192290328?s=400&u=ca6b769756b7be31a76e9d1d0e959fb91c24821a&v=4


[![GitHub](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white)](https://github.com/gonzalezmendez)
[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/alfredogonzalezmendez/)
[![Email](https://img.shields.io/badge/Email-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:gonzalez.mendez@hotmail.com)
