name: Sync Profile README
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada d√≠a
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Fetch README
        run: |
          curl -o README.md https://raw.githubusercontent.com/gonzalezmendez/gonzalezmendez/blob/main/README.md
          
      - name: Commit and Push
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README from profile" || exit 0
          git push
